on: [push]

jobs:
  # regula_job:
  #   runs-on: ubuntu-latest
  #   name: Regula
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Regula
  #     id: regula
  #     uses: fugue/regula-action@v0.4.0
  #     with:
  #       terraform_directory: .
  #       rego_paths: /opt/regula/rules policies
  #     env:
  #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform security scan
        uses: triat/terraform-security-scan@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
